### ISSUE TITLE
Добавить возможность шифрования сообщений (мемо) + Чаты (наброски)

### ISSUE THREAD

**Issue by serdrdoor** [golos-blockchain/ui-blogs#139]
**1. Добавить возможность шифрования сообщений (мемо).**
По дефолту и сейчас сообщение отправляемое не шифруется.
Но возможность такая есть, о чём свидетельствует наличие ключей MEMO.
Также эта коробочная фича Графен форков.

**В UI:**
- при отправке сообщения, ниже отображать галку "Шифровать сообщение", при активности которой сообщение будет зашифровано приватным ключом  _отправителя_ на публичный ключ _получателя_ (т.е. прочитать они смогут оба)
- в истории аккаунта отображать **Зашифрованное сообщение" - распознавать его например по уговоренному префиксу "encrypt::" - у тех аккаунтов, ключи которых не могут его расшифровать

**Варианты использования:**
- написание приватных сообщений пользователям, например деловые предложения, передача инвайта в зашифрованном виде другому юзеру
- сокрытие информации от всеобщего доступа для надстроек-приложений на блокчейне Golos (например при делании ставки на курс криптовалюты - чтобы не видеть чужих позиций и не увеличить свою вероятность победы в неком букмекере)
- проведение голосований/опросов в закрытую (с раскрытием ключа после завершения - например для проверки результатов или публичности), чтобы ход опроса не влиял на тех кто ещё не принял своё решение - чтобы исключить фактор влияния и подражания.

**2. Переписки в чатах (наброски)**
(логичнее сделать в последствии отдельной задачей):

Реализовать подобие ЧАТА (варианты реализации: надстройкой либо плагином в core) с приватной перепиской
Возможности:
1. создание чата (генерирование ключей для чата, не юзать свои личные)

2. удаление чата (точнее записи ключей закреплённых за чатом) (в UI в свою очередь не производить расшифровку без явного указания ключей в мета-инфе чата)

3. подумать над вариантом создать алго для псевдопредсказуемой генерации ключей для приватных чатов (чтобы можно было не запоминать в последствии  - а генерировать "на лету" в интерфейсе) по определённым правилам (пример реализации генерирования ключей в кошельке биткоина, либо аккаунтов на основе корневого в Bitshares - когда импортируешь корневой и сразу подхватываются все остальные аккаунты с ключами)

4. в любой момент иметь возможность перегенерировать и поменять ключ на чат (у создателя чата)

5. Роли: создатель/участник/модератор
 создатель - писать, раздавать юзерам роли (право повысить участника до модератора)
 участник - писать в чат и возможность быть ограниченным модератором или создеталем
 модератор - писать сообщения, может ограничивать пользователей в праве записи в чат
* то что написано в п.5 про Роли - моё видение базовых возможностей,, необходимо согласование с реальностью - с возможностями плагина CHAT.

Просмотреть какие возможности предоставляет плагин chat и с какими сущностями он работает - для выработки более детального ТЗ и оптимального пути дальнейшей интеграции.

**Comment by ksantoprotein** [comment]
"при отправке сообщения, ниже отображать галку "Шифровать сообщение", при активности которой сообщение будет зашифровано приватным ключом отправителя на публичный ключ получателя (т.е. прочитать они смогут оба)"

так в "коробочных решениях" мессаг начинался с решетки, это есть указание что мемо зашифрованное
