### ISSUE TITLE
Портирование сервиса для OAuth с API

### ISSUE THREAD

**Issue by Lex-Ai** [golos-blockchain/ui-blogs#38]
Необходим сервис OAuth с API, аналог https://github.com/steemit/steemconnect или https://github.com/ledgerconnect/hivesigner (https://hivesigner.com/developers). Возможно как-то объединить с наработками https://github.com/blckchnd/cryptoinvoice.app

Для того чтобы предоставить приложениям и сервисам "доверенный вариант" подписи транзакций без необходимости вводить ключи непонятно где.

**Comment by 0n0t0le** [comment]
Бабушки оценят)

**Comment by Lex-Ai** [comment]
На примере трансфера, востребована такая возможность

https://golos.id/transfers?to=thallid&amount=100.000&token=golos&memo=good

и как это работает на Стимит через steemconnect напр.

https://beta.steemconnect.com/sign/transfer?to=thallid&amount=1.00%20STEEM&memo=good
